[package]
name = "pome"
version = "0.0.6"
edition = "2024"

description = "A terminal-based text editor built with Ratatui."
license = "MIT OR Apache-2.0"

readme = "README.md"
repository = "https://github.com/Hendisil-Morier/pome"
homepage = "https://github.com/Hendisil-Morier/pome"

[dependencies]
dirs = "6.0.0"
mlua = { version = "^0.12.0", features = ["lua55", "vendored", "serialize"] }
ratatui = {version = "^0.30.2", features = ["serde"]}
ropey = "^1.6.1"
rust-embed = "8.12.0"
serde = {version = "^1.0.228", features = ["derive"]}

[lints.clippy]
needless_return = "allow"
